#!/bin/bash
#
# selfcontrol-focus-setup.sh
#
# Interactive wizard for configuring the SelfControl focus-block automation.
# Writes the schedule/blocklist to the config file, and regenerates/reloads
# TWO LaunchAgents from it:
#   - the reminder (fires at your scheduled time, sends a notification only)
#   - the watcher (always running, notifies + tracks streak when a block
#     actually starts/ends, however it was started)
# Starting a block itself is never scheduled -- see selfcontrol-focus.sh
# and selfcontrol-focus-reminder.sh for why.
#
# Usage:
#   selfcontrol-focus-setup.sh            interactive wizard (prompts for everything)
#   selfcontrol-focus-setup.sh --apply    non-interactive: just regenerate both plists
#                                         from whatever is currently in the config
#                                         file (use this after hand-editing the conf)

set -u

CONF_FILE="$HOME/.config/selfcontrol-focus/selfcontrol-focus.conf"
REMINDER_PLIST_PATH="$HOME/Library/LaunchAgents/local.selfcontrol-focus-reminder.plist"
WATCH_PLIST_PATH="$HOME/Library/LaunchAgents/local.selfcontrol-focus-watch.plist"
REMINDER_SCRIPT_PATH="$HOME/.local/bin/selfcontrol-focus-reminder.sh"
WATCH_SCRIPT_PATH="$HOME/.local/bin/selfcontrol-focus-watch.sh"
STARTER_SCRIPT_PATH="$HOME/.local/bin/selfcontrol-focus.sh"
DEFAULT_BLOCKLIST="$HOME/.config/selfcontrol-focus/SelfControlBlocklist-DeepWork.selfcontrol"
REMINDER_LABEL="local.selfcontrol-focus-reminder"
WATCH_LABEL="local.selfcontrol-focus-watch"
LOG_FILE="$HOME/Library/Logs/selfcontrol-focus.log"
ERROR_LOG_FILE="$HOME/Library/Logs/selfcontrol-focus-error.log"

DAY_NAMES=(Sunday Monday Tuesday Wednesday Thursday Friday Saturday)

load_existing_conf() {
    BLOCKLIST_PATH="$DEFAULT_BLOCKLIST"
    DURATION_MINUTES=120
    SCHEDULE_WEEKDAYS="1 2 3 4 5"
    START_HOUR=15
    START_MINUTE=0
    if [ -f "$CONF_FILE" ]; then
        # shellcheck disable=SC1090
        source "$CONF_FILE"
    fi
}

prompt_with_default() {
    local prompt="$1" default="$2" answer
    read -r -p "$prompt [$default]: " answer
    if [ -z "$answer" ]; then
        echo "$default"
    else
        echo "$answer"
    fi
}

validate_weekdays() {
    local input="$1" w
    for w in $input; do
        if ! [[ "$w" =~ ^[0-6]$ ]]; then
            echo "Invalid weekday '$w' -- use numbers 0-6 (0=Sunday, 1=Monday ... 6=Saturday)." >&2
            return 1
        fi
    done
    return 0
}

format_duration() {
    local total="$1"
    local h=$(( total / 60 ))
    local m=$(( total % 60 ))
    printf '%dh %02dm (%d minutes)' "$h" "$m" "$total"
}

# SelfControl cannot be stopped early once a block starts -- not by this
# script, not by the GUI, not at all. That's by design. Daily blocks you
# start yourself in the GUI are already capped at 24h by the app itself;
# this specifically guards selfcontrol-focus.sh's --test/manual-start path,
# which calls the CLI directly and isn't limited by the GUI's own slider.
confirm_long_duration() {
    if [ "$DURATION_MINUTES" -le 1440 ]; then
        return 0
    fi
    echo ""
    echo "This is a $(format_duration "$DURATION_MINUTES") block."
    echo "SelfControl CANNOT be stopped early once it starts -- no cancel, no override, by design."
    echo "If this duration is a mistake, it will run for the full length regardless."
    read -r -p "Type YES (all caps) to confirm you really want a block this long: " confirm_long
    if [ "${confirm_long:-}" != "YES" ]; then
        echo "Cancelled -- nothing was changed."
        exit 0
    fi
}

write_conf() {
    cat > "$CONF_FILE" <<EOF
# selfcontrol-focus.conf
# Generated by selfcontrol-focus-setup.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')
#
# You can hand-edit this file directly. After editing, apply the change by
# running:  selfcontrol-focus-setup.sh --apply
# (this regenerates and reloads the LaunchAgent plist from these values)

# Absolute path to the .selfcontrol blocklist file used for
# selfcontrol-focus.sh's manual/--test start (not used to auto-start anything).
BLOCKLIST_PATH="$BLOCKLIST_PATH"

# Suggested block length, in minutes -- shown in the reminder notification
# and used by selfcontrol-focus.sh's manual/--test start. You still pick the
# actual duration yourself in the SelfControl GUI when you press Start there.
# (the wizard asks for this as hours + minutes and converts it here)
DURATION_MINUTES=$DURATION_MINUTES

# Which days the reminder notification fires on.
# launchd weekday numbers: 0=Sunday 1=Monday 2=Tuesday 3=Wednesday 4=Thursday 5=Friday 6=Saturday
SCHEDULE_WEEKDAYS="$SCHEDULE_WEEKDAYS"

# Reminder time (24-hour clock, local time).
START_HOUR=$START_HOUR
START_MINUTE=$START_MINUTE
EOF
    echo "Wrote config: $CONF_FILE"
}

write_reminder_plist() {
    local weekday_entries=""
    local w
    for w in $SCHEDULE_WEEKDAYS; do
        weekday_entries+="        <dict>
            <key>Weekday</key>
            <integer>${w}</integer>
            <key>Hour</key>
            <integer>${START_HOUR}</integer>
            <key>Minute</key>
            <integer>${START_MINUTE}</integer>
        </dict>
"
    done

    mkdir -p "$HOME/Library/LaunchAgents"
    cat > "$REMINDER_PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${REMINDER_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>${REMINDER_SCRIPT_PATH}</string>
    </array>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>

    <key>StartCalendarInterval</key>
    <array>
${weekday_entries}    </array>

    <key>RunAtLoad</key>
    <false/>

    <key>StandardOutPath</key>
    <string>${LOG_FILE}</string>

    <key>StandardErrorPath</key>
    <string>${ERROR_LOG_FILE}</string>
</dict>
</plist>
EOF
    echo "Wrote LaunchAgent: $REMINDER_PLIST_PATH"
}

write_watch_plist() {
    mkdir -p "$HOME/Library/LaunchAgents"
    cat > "$WATCH_PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${WATCH_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>${WATCH_SCRIPT_PATH}</string>
    </array>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>

    <key>KeepAlive</key>
    <true/>

    <key>RunAtLoad</key>
    <true/>

    <key>StandardOutPath</key>
    <string>${LOG_FILE}</string>

    <key>StandardErrorPath</key>
    <string>${ERROR_LOG_FILE}</string>
</dict>
</plist>
EOF
    echo "Wrote LaunchAgent: $WATCH_PLIST_PATH"
}

reload_one_agent() {
    local plist_path="$1"
    launchctl unload "$plist_path" >/dev/null 2>&1
    if launchctl load "$plist_path" 2>/tmp/selfcontrol-setup-load-err.$$; then
        echo "Loaded: $plist_path"
    else
        echo "launchctl load failed for $plist_path:"
        cat /tmp/selfcontrol-setup-load-err.$$
    fi
    rm -f /tmp/selfcontrol-setup-load-err.$$
}

reload_agents() {
    reload_one_agent "$REMINDER_PLIST_PATH"
    reload_one_agent "$WATCH_PLIST_PATH"
}

summarize() {
    echo ""
    echo "Reminder summary:"
    local names="" w
    for w in $SCHEDULE_WEEKDAYS; do
        names+="${DAY_NAMES[$w]} "
    done
    printf '  Days:               %s\n' "$names"
    printf '  Reminder time:      %02d:%02d local time\n' "$START_HOUR" "$START_MINUTE"
    printf '  Suggested duration: %s (you still pick this yourself in the GUI)\n' "$(format_duration "$DURATION_MINUTES")"
    printf '  Blocklist:          %s (used by --test / manual start only)\n' "$BLOCKLIST_PATH"
    echo ""
    echo "The reminder only notifies -- it never starts a block itself."
    echo ""
}

apply_only() {
    load_existing_conf
    if [ ! -f "$CONF_FILE" ]; then
        echo "No config file found at $CONF_FILE -- run the wizard without --apply first." >&2
        exit 1
    fi
    if ! validate_weekdays "$SCHEDULE_WEEKDAYS"; then
        exit 1
    fi
    if ! [[ "$DURATION_MINUTES" =~ ^[0-9]+$ ]] || [ "$DURATION_MINUTES" -le 0 ]; then
        echo "DURATION_MINUTES in $CONF_FILE must be a positive integer." >&2
        exit 1
    fi
    summarize
    confirm_long_duration
    write_reminder_plist
    write_watch_plist
    reload_agents
}

interactive_wizard() {
    load_existing_conf

    echo "SelfControl focus-block scheduler setup"
    echo "----------------------------------------"
    echo ""

    echo "The reminder only sends a notification -- it never starts a block itself."
    echo "You start blocks yourself, either from the notification (opens SelfControl.app)"
    echo "or with selfcontrol-focus.sh for a quick manual/test start."
    echo ""

    while :; do
        SCHEDULE_WEEKDAYS="$(prompt_with_default "Days to remind on (space separated, 0=Sun..6=Sat, e.g. '1 2 3 4 5' for Mon-Fri)" "$SCHEDULE_WEEKDAYS")"
        if validate_weekdays "$SCHEDULE_WEEKDAYS"; then
            break
        fi
    done

    while :; do
        START_HOUR="$(prompt_with_default "Reminder hour (0-23, local time)" "$START_HOUR")"
        START_MINUTE="$(prompt_with_default "Reminder minute (0-59)" "$START_MINUTE")"
        if [[ "$START_HOUR" =~ ^[0-9]+$ ]] && [ "$START_HOUR" -ge 0 ] && [ "$START_HOUR" -le 23 ] \
           && [[ "$START_MINUTE" =~ ^[0-9]+$ ]] && [ "$START_MINUTE" -ge 0 ] && [ "$START_MINUTE" -le 59 ]; then
            break
        fi
        echo "Hour must be 0-23 and minute 0-59."
    done

    # Blocklist and duration are only used by the optional
    # selfcontrol-focus.sh --test/manual-start shortcut, not by the
    # reminder-and-GUI flow this wizard is actually setting up -- defaulted
    # silently rather than asked, so this only asks what your flow needs.
    if [ ! -f "$BLOCKLIST_PATH" ]; then
        BLOCKLIST_PATH="$DEFAULT_BLOCKLIST"
    fi

    summarize
    confirm_long_duration
    read -r -p "Save this and (re)load the LaunchAgents now? [Y/n]: " confirm
    if [ "$confirm" = "n" ] || [ "$confirm" = "N" ]; then
        echo "Nothing written. Run this wizard again when ready."
        exit 0
    fi

    write_conf
    write_reminder_plist
    write_watch_plist
    reload_agents

    echo ""
    echo "Done. A reminder will notify you at the configured times -- it won't start"
    echo "anything on its own. The watcher is now running in the background"
    echo "(launchd keeps it alive) and will notify you + track your streak whenever"
    echo "a block actually starts and finishes, however it was started."
    echo "To test the whole flow right now, run:"
    echo "  $STARTER_SCRIPT_PATH --test"
}

if [ "${1:-}" = "--apply" ]; then
    apply_only
else
    interactive_wizard
fi
