#!/usr/bin/env node
/**
 * Builds the playable demo at docs/demo/ from the real extension.
 *
 * A script rather than a hand-copied folder, for one reason: a demo that
 * drifts from the extension is worse than no demo. This copies the actual
 * shipped files every time, so the thing people try before installing is the
 * thing they install. Run by `npm run build:demo`, and `npm run check`
 * verifies the copy is current.
 *
 * The only addition is a shim standing in for the `chrome.*` APIs a page
 * gets inside an extension and does not get on a website. It is backed by
 * localStorage, so a demo day survives a refresh and still never leaves the
 * reader's browser — the same promise the extension itself makes.
 */

import { readFileSync, writeFileSync, mkdirSync, cpSync, rmSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "docs", "demo");

/** Everything the page loads. Kept in step with the package script by
 *  check-package.mjs, which walks the same import graph. */
const FILES = [
  "dial.html", "dial.css", "dial.js", "i18n.js", "lib.js",
  "history.js", "historyLib.js", "drive.js", "suggestions.js",
];

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
for (const f of FILES) cpSync(join(root, f), join(out, f));
cpSync(join(root, "_locales"), join(out, "_locales"), { recursive: true });
cpSync(join(root, "fonts"), join(out, "fonts"), { recursive: true });
if (existsSync(join(root, "icons"))) cpSync(join(root, "icons"), join(out, "icons"), { recursive: true });

const version = JSON.parse(readFileSync(join(root, "manifest.json"), "utf8")).version;

const shim = `/*
 * Stands in for the chrome.* APIs the extension has and a web page does not.
 * Generated by scripts/build-demo.mjs — edit that, not this.
 *
 * Storage is localStorage, so a day painted here survives a refresh and
 * still never leaves this browser. Nothing is sent anywhere, which is the
 * same promise the extension makes and would be a strange one to break on
 * the page that advertises it.
 */
(function () {
  const KEY = "dailyDialDemo";
  const load = () => { try { return JSON.parse(localStorage.getItem(KEY)) || {}; } catch { return {}; } };
  const save = (s) => { try { localStorage.setItem(KEY, JSON.stringify(s)); } catch { /* private window */ } };
  const store = load();
  const noop = () => {};
  const listeners = () => ({ addListener: noop, removeListener: noop, hasListener: () => false });

  const req = (path) => {
    const x = new XMLHttpRequest();
    x.open("GET", path, false);
    try { x.send(); return x.status === 200 || x.status === 0 ? JSON.parse(x.responseText) : null; }
    catch { return null; }
  };
  const lang = (navigator.language || "en").toLowerCase();
  const pick = ${JSON.stringify(["ar","de","en","es","fr","hi","ja","pt_BR","ru","zh_CN"])}
    .find((l) => lang.startsWith(l.toLowerCase().split("_")[0])) || "en";
  const MSGS = req("_locales/" + pick + "/messages.json") || {};
  const EN = pick === "en" ? MSGS : (req("_locales/en/messages.json") || {});

  window.chrome = {
    runtime: {
      id: "demo", lastError: null,
      getURL: (p) => new URL(p, location.href).href,
      getManifest: () => ({ version: ${JSON.stringify(version)} }),
      sendMessage: () => Promise.resolve({}),
      onMessage: listeners(), getContexts: () => Promise.resolve([]),
    },
    storage: {
      local: {
        get: (keys) => {
          let o = {};
          if (keys == null) o = { ...store };
          else if (typeof keys === "string") { if (keys in store) o[keys] = store[keys]; }
          else if (Array.isArray(keys)) keys.forEach((k) => { if (k in store) o[k] = store[k]; });
          else Object.keys(keys).forEach((k) => { o[k] = k in store ? store[k] : keys[k]; });
          return Promise.resolve(o);
        },
        set: (o) => { Object.assign(store, JSON.parse(JSON.stringify(o))); save(store); return Promise.resolve(); },
        remove: (k) => { (Array.isArray(k) ? k : [k]).forEach((x) => delete store[x]); save(store); return Promise.resolve(); },
        clear: () => { Object.keys(store).forEach((k) => delete store[k]); save(store); return Promise.resolve(); },
        getBytesInUse: () => Promise.resolve(JSON.stringify(store).length),
      },
      onChanged: listeners(),
    },
    // Reminders and Drive need a real extension. They are visible in the demo
    // so the settings screen is honest about what exists, and simply do
    // nothing here.
    alarms: { create: noop, clear: () => Promise.resolve(true), getAll: () => Promise.resolve([]), onAlarm: listeners() },
    notifications: { create: noop, clear: noop, onClicked: listeners(), onButtonClicked: listeners() },
    identity: { getAuthToken: (o, cb) => cb && cb(undefined), removeCachedAuthToken: (o, cb) => cb && cb() },
    permissions: { contains: () => Promise.resolve(false), request: () => Promise.resolve(false), remove: () => Promise.resolve(true) },
    action: { onClicked: listeners(), setBadgeText: () => Promise.resolve(), setBadgeBackgroundColor: () => Promise.resolve() },
    i18n: {
      getUILanguage: () => pick.replace("_", "-"),
      getMessage: (key, subs) => {
        const e = MSGS[key] || EN[key];
        if (!e) return "";
        let s = e.message;
        const args = subs === undefined ? [] : Array.isArray(subs) ? subs : [subs];
        const ph = e.placeholders || (EN[key] && EN[key].placeholders);
        if (ph) for (const [n, d] of Object.entries(ph)) {
          const i = parseInt(String(d.content).replace("$", ""), 10) - 1;
          s = s.replace(new RegExp("\\\\$" + n + "\\\\$", "gi"), args[i] ?? "");
        }
        return s;
      },
    },
  };
})();
`;
writeFileSync(join(out, "demo-shim.js"), shim);

// A banner naming what this is, and the two things it cannot do.
const banner = `    <div style="max-width:1180px;margin:0 auto;padding:10px 16px;font:14px/1.5 system-ui,sans-serif;
                display:flex;gap:12px;align-items:center;flex-wrap:wrap;
                border-bottom:1px solid rgba(128,128,128,0.25)">
      <strong>Demo.</strong>
      <span style="opacity:0.8">Everything works and stays in this browser. Reminders and Google Drive backup need the real extension.</span>
      <a href="https://chromewebstore.google.com/detail/daily-dial/mgcjgngceajnmfhkifccaoeccbmfikhn"
         style="margin-left:auto;font-weight:700">Install it</a>
      <a href="../index.html">Back to the site</a>
    </div>
`;

let html = readFileSync(join(out, "dial.html"), "utf8");
html = html.replace("</head>", '  <script src="demo-shim.js"></script>\n</head>');
html = html.replace(/(<body[^>]*>)/, `$1\n${banner}`);
writeFileSync(join(out, "index.html"), html);
rmSync(join(out, "dial.html"));

console.log(`docs/demo/ built from v${version} — ${FILES.length} modules, shimmed for the web`);
